<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>CircuitLordVRModInstaller</AssemblyName>
    <RootNamespace>BigWalkVRInstaller</RootNamespace>
    <Version>1.2.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="Assets\big-walk.jpg" />
    <Resource Include="Assets\titanfall-2.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
